services:
  app:
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro

  mysql:
    restart: unless-stopped
    ports: []

  phpmyadmin:
    profiles: ["dev"]
